export interface TranslationType {
  welcome: string;
  intro1Parts: {
    prefix: string;
    highlight: string;
    suffix: string;
  };
  intro1: string;
  intro2: string;
  intro3: string;
  yesterdayPrice: string;
  priceExplanation: string;
  lastUpdated: string;
  loading: string;
  failedLoad: string;
  calculator: string;
  calculatorNote: string;
  investmentAmount: string;
  buyingPrice: string;
  summary: string;
  unitsOwned: string;
  potentialReturn: string;
  profitLoss: string;
  summaryNote: string;
  subscribe: string;
  subscribeNote: string;
  emailAddress: string;
  subscribeButton: string;
  enterDetails: string;
}

export const translations: { en: TranslationType; id: TranslationType } = {
  en: {
    welcome: "Welcome to AXA-Mandiri Insurance Investment Fund Tracker",
    intro1Parts: {
      prefix: "Hi, I created this website to help you track the price of AXA-Mandiri Insurance Investment Fund, to be specific the price of the ",
      highlight: "Mandiri Attractive Equity Money Rupiah (ATRP)",
      suffix: ".",
    },
    intro1: "Hi, I created this website to help you track the price of AXA-Mandiri Insurance Investment Fund, to be specific the price of the Mandiri Attractive Equity Money Rupiah (ATRP).",
    intro2: "The reason I created this website is to help the owner of this investment fund to easily track the selling price and make an informed decision to reduce the loss generated by this poor investment product.",
    intro3: "If you need other AXA-Mandiri insurance investment products other than ATRP to be listed here, just drop me an email using the email button on the bottom of this app.",
    yesterdayPrice: "Yesterday's Sell Price",
    priceExplanation: "If you sell your investment to AXA-Mandiri yesterday, this is the price per unit you will get.",
    lastUpdated: "Last updated",
    loading: "Loading...",
    failedLoad: "Failed to load price",
    calculator: "Investment Calculator",
    calculatorNote: "Use this simple calculator to generate an estimate of the potential returned fund amount. The investment amount and the buying price are available in your insurance policy or monthly investment email update.",
    investmentAmount: "Investment Amount (IDR)",
    buyingPrice: "Unit Buying Price (IDR)",
    summary: "Investment Summary",
    unitsOwned: "Number of Units Owned",
    potentialReturn: "Potential Returned Fund Amount",
    profitLoss: "Estimated Profit/Loss",
    summaryNote: "This summary is generated based on yesterday's selling price",
    subscribe: "Subscribe for Updates",
    subscribeNote: "If you want to get a daily update of the selling price, please enter your email address below.",
    emailAddress: "Email Address",
    subscribeButton: "Subscribe",
    enterDetails: "Enter investment amount and buying price to see potential return"
  },
  id: {
    welcome: "Selamat Datang di Pelacak Dana Investasi Asuransi AXA-Mandiri",
    intro1Parts: {
      prefix: "Hai, saya membuat website ini untuk membantu Anda melacak harga Dana Investasi Asuransi AXA-Mandiri, khususnya harga ",
      highlight: "Mandiri Attractive Equity Money Rupiah (ATRP)",
      suffix: ".",
    },
    intro1: "Hai, saya membuat website ini untuk membantu Anda melacak harga Dana Investasi Asuransi AXA-Mandiri, khususnya harga Mandiri Attractive Equity Money Rupiah (ATRP).",
    intro2: "Alasan saya membuat website ini adalah untuk membantu pemilik dana investasi ini untuk dengan mudah melacak harga jual dan membuat keputusan yang tepat untuk mengurangi kerugian yang dihasilkan oleh produk investasi yang buruk ini.",
    intro3: "Jika Anda membutuhkan produk investasi asuransi AXA-Mandiri selain ATRP untuk ditampilkan di sini, silakan kirim email menggunakan tombol email di bagian bawah aplikasi ini.",
    yesterdayPrice: "Harga Jual Kemarin",
    priceExplanation: "Jika Anda menjual investasi Anda ke AXA-Mandiri kemarin, ini adalah harga per unit yang akan Anda dapatkan.",
    lastUpdated: "Terakhir diperbarui",
    loading: "Memuat...",
    failedLoad: "Gagal memuat harga",
    calculator: "Kalkulator Investasi",
    calculatorNote: "Gunakan kalkulator sederhana ini untuk menghasilkan perkiraan jumlah dana yang berpotensi dikembalikan. Jumlah investasi dan harga beli tersedia di polis asuransi Anda atau email update investasi bulanan.",
    investmentAmount: "Jumlah Investasi (IDR)",
    buyingPrice: "Harga Beli Unit (IDR)",
    summary: "Ringkasan Investasi",
    unitsOwned: "Jumlah Unit yang Dimiliki",
    potentialReturn: "Potensi Jumlah Dana Kembali",
    profitLoss: "Estimasi Untung/Rugi",
    summaryNote: "Ringkasan ini dihasilkan berdasarkan harga jual kemarin",
    subscribe: "Berlangganan Update",
    subscribeNote: "Jika Anda ingin mendapatkan update harga jual harian, silakan masukkan alamat email Anda di bawah ini.",
    emailAddress: "Alamat Email",
    subscribeButton: "Berlangganan",
    enterDetails: "Masukkan jumlah investasi dan harga beli untuk melihat potensi pengembalian"
  }
};
